### PR TITLE
No cmtf

### PR DESCRIPTION
**Pull request by murphymadeleine21**
So far, it doesn't look like it is improving much.. ADCC accuracy is .4305. Let me know if there is tweaking in the code that might make it better though?

### CODE REVIEW

**Comment by aarmey** [comment]
Have you varied the component #?

**Comment by murphymadeleine21** [comment]
No, I'll implement that now.

**Comment by murphymadeleine21** [comment]
ADCC Function Predictions:
CMTF R2X: 0.4362022809263445
Components: 1, Accuracy: 0.34720633605570234
CMTF R2X: 0.5581453872064253
Components: 2, Accuracy: 0.34587571039779297
CMTF R2X: 0.5977949975435362
Components: 3, Accuracy: 0.34427355056520925
CMTF R2X: 0.6461385245810258
Components: 4, Accuracy: 0.44428919226954927
CMTF R2X: 0.682784785769375
Components: 5, Accuracy: 0.42869839954866656
CMTF R2X: 0.6999904989689127
Components: 6, Accuracy: 0.40006632691483296
CMTF R2X: 0.7305107093671195
Components: 7, Accuracy: 0.43960478953261395
CMTF R2X: 0.7462812289060252
Components: 8, Accuracy: 0.4191375748768747
CMTF R2X: 0.7679727175449353
Components: 9, Accuracy: 0.3627641353046937
CMTF R2X: 0.7809103478801004
Components: 10, Accuracy: 0.3807523186666304

**Comment by aarmey** [comment]
This is R or R2?

**Comment by murphymadeleine21** [comment]
sqrt(R2)

**Comment by aarmey** [comment]
Ok. You probably want to try much higher component numbers—like ~15-20. An R2X of 0.78 indicates there's quite a bit of variance that can still be captured.

**Comment by murphymadeleine21** [comment]
CMTF R2X: 0.7921171877669049
Components: 11, Accuracy: 0.39213375294723735
CMTF R2X: 0.8105194610287407
Components: 12, Accuracy: 0.400508498128808
CMTF R2X: 0.82511438692447
Components: 13, Accuracy: 0.44394792987974335
CMTF R2X: 0.8354595074687345
Components: 14, Accuracy: 0.4523151581266568
CMTF R2X: 0.8410384764480098
Components: 15, Accuracy: 0.478765051895924
CMTF R2X: 0.8546989093232318
Components: 16, Accuracy: 0.4614799809119427
CMTF R2X: 0.8644237994752424
Components: 17, Accuracy: 0.4650153698014316
CMTF R2X: 0.8733348451517792
Components: 18, Accuracy: 0.4562974851448609
CMTF R2X: 0.8787271385241879
Components: 19, Accuracy: 0.4713550834691745
CMTF R2X: 0.8861954655652462
Components: 20, Accuracy: 0.470856228369165

**Comment by aarmey** [comment]
Hmm... so first, looking at Alter et al, it looks like I was mistaken and ADCC does require some of the glycan measurements. MIP1b does not, however. So, if MIP1b is predicted similarly to Alter, then I wouldn't worry about the lower ADCC performance for now.

Another thought I had over the weekend is that, after the data reduction (factorization), the relationship with function doesn't really have to be linear. If the function predictions remain lower, even as we're hitting this R2X plateau, we can try a more flexible regression method like support vector regression. We can discuss this more tomorrow.

**Comment by murphymadeleine21** [comment]
Okay. Unfortunately, it does not seem like MIP1b is preforming as well as Alter. This is the highest accuracy:
Components: 15, Accuracy: 0.478765051895924
Alters is around .6-.65 I believe

**Pull request closed without merging**
