### PR TITLE
ADCC component figure

### PR DESCRIPTION
**Pull request by murphymadeleine21**
Plotting each component against the ADCC data, with subjects labeled. 

Struggled with a nice way to replace True/False values with "Alter"/"Leftout Alter" using numpy array functions, if you know of any syntax tricks to do without a for loop. Couldn't find much online that didn't involve mapping using a DF.

### CODE REVIEW

**Review by aarmey — APPROVED** [review]
This is great. It does look like the non-Alter subjects are different on the higher components. On a new branch, could you try going back to only fitting with the Alter subjects? We've made a bunch of changes since trying that last...

**Comment by murphymadeleine21** [comment]
When you say only fitting with Alter subjects, which part do you mean? For example, we have the option to only fit with Alter subjects, and we're already doing that in Figure 2a. Figure 2c we do subjects left out of Alter. I don't believe we do any fitting elsewhere. In fact, I think we aren't calling `function_prediction `with evaluation set to `all` anywhere as of now.

**Comment by aarmey** [comment]
We currently fit with all the subjects, then isolate the Alter subjects when evaluating the performance of the model.

**Comment by aarmey** [comment]
Currently, we *always* fit with all the subjects. That’s what I’m suggesting we change.

**Comment by murphymadeleine21** [comment]
Ah I see, I forgot we had changed that around and were back to fitting with all of them.

**Pull request merged**
