### PR TITLE
Fig 3C, Increasing imputation fraction

### PR DESCRIPTION
**Pull request by murphymadeleine21**
So far it seems to be working pretty well with both PCA and CMTF, although there seem to be a few issues:
1. When we get to like .99 fraction missing, CMTF R2X drops below 0.
2. At some point when `PCAcompare=True` (need to find out exactly at what fraction this occurs at) we get an error with trying to flatten the cube into a matrix. I wonder if this has to do with entire rows/columns missing? Will look into more tomorrow/we can discuss in meeting.

### CODE REVIEW

**Comment by murphymadeleine21** [comment]
@cyrillustan I might try to begin working on taking the averages/error bars for the imputations but they may need to go on a separate branch? Let me know what you think of this one and we can go from there.

**Comment by cyrillustan** [comment]
You can use the same branch. This is unfinished work anyway

**Comment by murphymadeleine21** [comment]
Screen Shot 2021-04-27 at 11 44 41 AM
@cyrillustan This is an image I just made in a notebook, after this figure fully builds it should look something like this. At first I thought it wasn't working because it looks like the errorbars aren't there past the first value, but I actually realized those stds are just really really small. This is basically done except I can't get the PCA error bar color to match the exact seaborn colorblind palette we use to set up these figures, so I was wondering if you knew how to fix that?

**Comment by murphymadeleine21** [comment]
Not sure why but the latest build didn't even make figure3

**Comment by murphymadeleine21** [comment]
Oh, weird it had gotten deleted from the makefile. Possibly from the branch merge. Nice edits, I like the way you rearranged it and always learn a lot from how you choose to do it haha.

**Comment by cyrillustan** [comment]
> Oh, weird it had gotten deleted from the makefile. Possibly from the branch merge. Nice edits, I like the way you rearranged it and always learn a lot from how you choose to do it haha.

Yes, that was from a previous edit from Dr. Meyer. This should make everything for Fig. 3, let see how well it builds.

**Pull request merged**
