### PR TITLE
Changes in Fig 6, remove Fig 6c and add ROC curves

### PR DESCRIPTION
**Pull request by cyrillustan**

### CODE REVIEW

**Comment by cyrillustan** [comment]
@Kimeiga for Fig 6d here, we want to label the subjects by groups just like in Fig 5a. Can you do this?

**Comment by Kimeiga** [comment]
Yeah I'll go for it tomorrow

**Comment by cyrillustan** [comment]
@Kimeiga I'll merge this. You can start a new branch for adding subject information.

**Comment by Kimeiga** [comment]
Ok sorry for the delay I'm at CVS ATM but will add subject info when i get back

**Pull request merged**
