### PR TITLE
Assessment Methods

### PR DESCRIPTION
**Pull request by murphymadeleine21**

### CODE REVIEW

**Comment by murphymadeleine21** [comment]
There are a lot of changes happening in this branch to try to help with the assessment issue you opened yesterday. I think I've got pretty close to what you were discussing with running our regression with all of the subjects and then subsetting after for function predictions. I am now going to try to look at the classification predictions to do the same. Also trying to make sure it builds properly, as with all of the new changes it's having some build errors.

**Review by aarmey — COMMENTED** [review]
Ok, please tag me when it's building successfully or you need my input.

**Comment by murphymadeleine21** [comment]
I tried for so long to get AlterIndices (and other little blocks of code) to be one liners and kept having errors! Still getting the syntax down! Thank you for showing how to do it in one line

**Review by aarmey — CHANGES_REQUESTED** [review]
Much of your code could be considerably simplified by using Numpy methods and recognizing repeating patterns in different functions. Look through the changes I made to regression.py. I changed the function interface, so see if you can hook the figures back up. It's also possible I made an error or two. I'm happy to help if you're unsure about my changes.

**Comment by murphymadeleine21** [comment]
Yes, that does look good. I had tried using the numpy interface like you used (for example the insert function), but was running into errors.. Most likely due to my lack of background knowledge of Python. This looks much better though, I will fix the figures and keep working on trying to be more savvy with the interface & language.

**Comment by aarmey** [comment]
Sorry, didn't know you were doing the same here, but I just simplified the classification code and merged it with master. In case it's helpful, you can do `git checkout master -- FILE` to copy a file from master onto your branch.

**Comment by murphymadeleine21** [comment]
The notAlter predictions are now returning in different sizes, so I'm dealing with that issue now.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
