### PR TITLE
Make heatmap figure

### PR DESCRIPTION
**Pull request by murphymadeleine21**
First glances at the heatmaps. I think all of them actually fall pretty nicely into a natural order (for example, all the receptor 3s are in a row) besides perhaps glycans.

### CODE REVIEW

**Comment by aarmey** [comment]
Agreed that this is an improvement. See if you can clean it up (e.g. test not overlapping, diverging color palette so that zero is white, etc.)

**Comment by murphymadeleine21** [comment]
Here's one way to visualize it. However, in order for text to not overlap, we have to eliminate some of the labels and therefore won't be able to independently identify every row. I actually think this works okay for the receptors because you can clearly see a distinction between R3 and things like the IgGs. But with antigens and glycans, might be a bit less intuitive to figure out what you're looking at without the labels.

**Comment by aarmey** [comment]
This is again an improvement, but you're pointing out limitations we need to fix. The patients could probably just be labeled with some colored bar on the side to indicate their class, but the other measurements will need to be individually identifiable. One easy start would be to put all the plots in one row, so they can be taller. I'm confident that you can think creatively to come up with other adjustments. :-)

**Comment by murphymadeleine21** [comment]
This is definitely better and easier to read, but I'm running into a problem with the tick marks. It seems to ignore my input array of what I want the tickmarks to be on the colorbar, and I don't know why. From some googling, looks like this has happened to people before but it's somewhat unclear how to fix.

**Comment by murphymadeleine21** [comment]
Also, both antigens and receptors are all 0 for the last 6 components. We could consider showing only the first 6 on those heatmaps?

**Comment by aarmey** [comment]
Good point but let's leave those in—I'm hoping they can be filled in with some adjustments to the factorization.

**Comment by murphymadeleine21** [comment]
The readability is much better, the only issue at this point I think is the cbar ticks.

**Review by aarmey — CHANGES_REQUESTED** [review]
Excellent! This can replace figures 3 + 4, and you can make the figure size a bit wider so the component numbers all show, then we can merge this.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
