### PR TITLE
Hakan alter bootstrapping

### PR DESCRIPTION
**Pull request by Kimeiga**
image
I have tried 
`f.tight_layout()`
`f.subplots_adjust(hspace=10.0, wspace=1.0)`
and `subplotLabel()` (thinking it might handle the spacing too)

Nothing spaces the figures out properly. SOS.

After that is done, I think the figure is ready.

### CODE REVIEW

**Comment by cyrillustan** [comment]
Can you put more space into these subplots? They are overlapping.

**Comment by aarmey** [comment]
This is great! I have a subtle discomfort with this way of presenting things, but it will be easier to discuss tomorrow on Zoom.

**Comment by Kimeiga** [comment]
> Can you put more space into these subplots? They are overlapping.

haha I have tried 3 ways to no avail. I documented this on the slack thread too but when I tried different ways of spacing, it would make heights of the graphs tiny; I couldn't figure it out

**Comment by cyrillustan** [comment]
I think the built version here shows that the texts are complete, but the figures are too small

**Comment by Kimeiga** [comment]
Here is my attempt with `tight_layout()`
image
Here is my attempt with `f.subplots_adjust(hspace=10.0, wspace=1.0)`
image

It makes ample room for the labels and text, but then the graphs get too small. SOS

**Comment by aarmey** [comment]
Swap the x- and y-axes, then the text labels would be horizontal.

**Comment by Kimeiga** [comment]
current state:

**Comment by cyrillustan** [comment]
Btw, all supplemental figures will be call EV from now on. (So Fig. EV3 instead of Fig. S3)

**Comment by aarmey** [comment]
Note that I've put X scaling inside RegressionHelper, so you won't find it in this PR anymore.

**Comment by aarmey** [comment]
Merging!

**Pull request merged**
