### PR TITLE
Add PCA imputation to Figure 1

### PR DESCRIPTION
**Pull request by murphymadeleine21**
The PCA imputation seems to be working and resulting in pretty good R2X/Q2X (and reasonable?) values (~.88-.97). My make file is having issues for unknown reasons so I can't view the figures on my visual studio code but I'm hoping this turns out as a scatter plot, otherwise I can change it to be so.

### CODE REVIEW

**Comment by murphymadeleine21** [comment]
With your fixes, where are we artificially removing values from the matrix?

**Comment by scottdtaylor95** [comment]
I think in the call to PCA, tMat should be changed to imputeFlattened if we're trying to match the TMTF imputation

**Comment by murphymadeleine21** [comment]
I think you're right scott!

**Comment by scottdtaylor95** [comment]
One issue with this is that PCA doesn't allow for a whole column/row to be NaN, so it didn't work for me. Maybe we change which values are missing?

**Comment by aarmey** [comment]
Oh good catch both. You're right that this won't work for leaving out entire receptor-ligand pairs. Unfortunately I don't think we'll be able to add this then. We could leave out single values, but the entire receptor-ligand pairs approach is special because it's a very high bar as far as imputation goes. (The method knows something about the receptor, and something about the antigen, but not how they interact in any of the patients.)

**Pull request closed without merging**
