### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by murphymadeleine21**
This could potentially be one way to reorganize according to your comments, but let me know if it makes sense.

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
Resolve the conflicts but this looks like a good layout.

**Comment by murphymadeleine21** [comment]
It wanted me to fix the conflicts from the command line, I think I've done it correctly so let me know if this looks right. Haven't done it in command line before.

**Review by aarmey — CHANGES_REQUESTED** [review]
Looks like you handled the merge correctly. Only edit I see is: shouldn't `two_way_classifications()` go in classify.py?

**Comment by murphymadeleine21** [comment]
Sure. I wasn't sure because it doesn't directly use SVM but instead uses Logistic Regression. But I can put it there!

**Review by aarmey — APPROVED** [review]
Looks good! Logistic regression is a classification method, because it predicts a binary outcome.

**Comment by murphymadeleine21** [comment]
I was having some issues with merging/resolving conflicts an hour ago, so thank you for merging them, hopefully that can resolve the conflicts

**Pull request merged**
