### PR TITLE
R2X Components Figure

### PR DESCRIPTION
**Pull request by murphymadeleine21**
Here's the backbone of a function plotting R2X vs. component numbers, as you said in slack. I think I might be a bit confused about what you want because in Slack you said just plotting component numbers vs. R2X, but we're already doing that in Fig1A. Nonetheless, this is at least the backbone of a figure that plots R2X against Component numbers that we can build off of. Let me know if this is what you wanted and we can also talk more about this while meeting tomorrow.

### CODE REVIEW

**Comment by aarmey** [comment]
Oh I see... my description was incomplete. I meant we should look at the reconstruction error of *missing values*. Sorry that I left this out. Basically I mean we should go back to using the imputation code you wrote this summer.

**Comment by murphymadeleine21** [comment]
I changed the evaluate missing function such that if we find a missing value, we make it missing for all of the patients and store the value. Then we compare the reconstructed tensor (which has many missing values) to the original tensor.
In terms of plotting, right now we have it doing something that seems like an error essentially: orig-recon/recon. I'm not sure why it still says Sumsqs because I don't believe we're actually squaring anything anymore. But I wanted to check first if this is how you even want to compare the original and reconstructed values, or if there is a more desirable way. If this is the correct method, what is the appropriate title for its axis on the graph?

**Comment by aarmey** [comment]
If you're removing all the patients, why not store all those values?

The norm is the sum of squares for a vector or matrix: https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html

**Comment by aarmey** [comment]
Also, I've never liked that we remove different sets for different numbers of components. The same values should be removed and then compared in their imputation fidelity across differing numbers of components. Otherwise, some components will randomly get "easier" values and others will get harder ones. Try and rethink the organization of these functions.

**Comment by murphymadeleine21** [comment]
Okay, I see what you mean with the reorganizing. Re storing values, I believe we are. I save them all here `orig.append(cube[:, j, k])`

**Review by aarmey — CHANGES_REQUESTED** [review]
Check that this builds first.

**Review by aarmey — APPROVED** [review]
This was passing because Fig. S3 wasn't building before. I've added S3 to the build queue and manuscript.

I also made some changes to how the imputation is performed. A few general ideas:
- If you only call a function once, it's probably better to not have it as a separate function
- I changed the variable tracking to use the tensors, because this makes it easier to follow where the data comes from
- The sum of squares error is different from R2X. This was labelled as different things in each place. It now uses R2X throughout. One minor note—R2X is called Q2X when it's performed on cross-validation, which is essentially what imputation is.

**Pull request merged**
