### PR TITLE
Coefs

### PR DESCRIPTION
**Pull request by scottdtaylor95**

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
Looks great. My only change is this can go into Fig. 2.

**Comment by scottdtaylor95** [comment]
It should be added to figure 2, but figure 1 seems to be having issues (Error 1) and the following warning pops up many times in the build: "WARNING:Static argument (index _(1/2/3)_) of type <class 'numpy.ndarray'> for function cost is non-hashable. As this can lead to unexpected cache-misses, it will raise an error in a near future."

**Comment by aarmey** [comment]
Think I probably fixed that warning. For figure 1, look at the error—I think you can figure it out.

**Comment by aarmey** [comment]
(I moved your component evaluation into Fig. 1, so it now calls the regression function. You need to correct it to account for another return value.)

**Review by aarmey — APPROVED** [review]
Great!

**Pull request merged**
