### PR TITLE
To CMTF and other changes

### PR DESCRIPTION
**Pull request by aarmey**

### CODE REVIEW

**Comment by cyrillustan** [comment]
Wait, what does this do?

**Comment by aarmey** [comment]
It turns out the method we are using is just CMTF, so I'm starting on the text changes. I also have been exploring some different ways of normalizing the data. I thought I found something useful but was wrong, so I'll be reverting the normalization changes soon.

**Comment by cyrillustan** [comment]
Sounds like this can lead to a big change in the paper. We should definitely talk about this tomorrow; I'm a bit confused.

**Comment by aarmey** [comment]
There are still some methodological changes we made to get it to work. It seems that the CMTF implementation we were using was not correct. I’m not worried about the change at all—nobody mentioned TMTF as an advance, and application to biological data is still an important advancement.

**Pull request merged**
